# Config for TrekSafer

# The radius to search for fires within (km).
fire_radius: 50

# Maximum radius a user can specify (km).
max_radius: 150

# The default fire status filter level (active, controlled, all).
# controlled: includes active, managed, and controlled fires (excludes out)
# active: only active fires
# all/out: all fires including out fires
fire_status: "controlled"

# Minimum fire size to include (hectares).
fire_size: 1

# The amount of time to wait for a download before giving up, in seconds.
download_timeout: 600

# Include the AQI at the specified coordinates in the response.
include_aqi: true

# Path to shapefiles
shapefiles: "shapefiles"

# Logging
log_file: "logs/${TREKSAFER_ENV}.log"
# logging.INFO
log_level: 20

transports:
  - type: "signalwire"
    enabled: ${TREKSAFER_SW_ENABLED:-false}
    project_id: ${TREKSAFER_SW_PROJECT}
    api_token : ${TREKSAFER_SW_TOKEN}
    phone_number: "${TREKSAFER_SW_NUMBER}"
  - type: "cli"
    enabled: ${TREKSAFER_CLI_ENABLED:-true}
    host: ${TREKSAFER_CLI_HOST:-localhost}
    port: "${TREKSAFER_CLI_PORT:-8888}"

# Data files, located at {shapefiles}/{location}/{filename}.
data:
  - location: AB
    filename: AB_Fire_Perimeters_{DATE}.zip
    mapping:
      fields:
        Fire: FIRE_NUMBE
        Size: AREA
        Name: ALIAS
        Location: COMPLEX
        Status: STATUS
    status_map:
      active: ['Out of Control']
      managed: ['Being Held']
      controlled: ['Under Control']
      out: []
  - location: BC
    filename: BC_Fire_Perimeters_{DATE}.zip
    mapping:
      fields:
        Fire: FIRE_NUM
        Size: FIRE_SZ_HA
      api:
        url: https://wildfiresituation-api.nrs.gov.bc.ca/publicPublishedIncident/{FIRE_NUM}?fireYear={FIRE_YEAR}
        fields:
          Name: incidentName
          Location: incidentLocation
          Status: stageOfControlCode
    status_map:
      active: ['OUT_CNTRL']
      managed: ['HOLDING']
      controlled: ['UNDR_CNTRL']
      out: ['OUT']
  - location: CA
    filename: CA_Fire_Perimeters_{DATE}.zip
    mapping:
      fields:
        Fire: firename
        Name: firename
        Location: agency
        Size: hectares
        Status: stage_of_c
    status_map:
      active: ['OC']
      managed: ['BH']
      controlled: ['UC']
      out: []
  - location: US
    filename: "WFIGS_Interagency_Perimeters_{DATE}.zip"
    mapping:
      fields:
        Fire: attr_Fir_6
        Name: attr_Inc_2
        Location: attr_Inc_4
        Size: attr_Incid
        Status: attr_Fir_2
      size_transform: acres_to_hectares
    status_map:
      active: ['OUT_CNTRL']
      managed: ['Flanking', 'HOLDING']
      controlled: ['UC']
      out: ['OUT']
