# Config for TrekSafer

# The radius to search for fires within (km).
fire_radius: 50

# The amount of time to wait for a download before giving up, in seconds.
download_timeout: 600

# Path to shapefiles
shapefiles: "shapefiles"

# Logging
log_file: "logs/${TREKSAFER_ENV}.log"
# logging.INFO
log_level: 20

transports:
  - type: "signalwire"
    enabled: ${TREKSAFER_SW_ENABLED:-false}
    project_id: ${TREKSAFER_SW_PROJECT}
    api_token : ${TREKSAFER_SW_TOKEN}
    phone_number: "${TREKSAFER_SW_NUMBER}"
  - type: "cli"
    enabled: ${TREKSAFER_CLI_ENABLED:-true}
    host: ${TREKSAFER_CLI_HOST:-localhost}
    port: "${TREKSAFER_CLI_PORT:-8888}"

# Data files, located at {shapefiles}/{location}/{filename}.
data:
  - location: AB
    filename: AB_Fire_Perimeters_{DATE}.zip
    mapping:
      fields:
        Fire: FIRE_NUMBE
        Size: AREA
        Name: ALIAS
        Location: COMPLEX
        Status: STATUS
  - location: BC
    filename: BC_Fire_Perimeters_{DATE}.zip
    mapping:
      fields:
        Fire: FIRE_NUM
        Size: FIRE_SZ_HA
      api:
        url: https://wildfiresituation-api.nrs.gov.bc.ca/publicPublishedIncident/{FIRE_NUM}?fireYear={FIRE_YEAR}
        fields:
          Name: incidentName
          Location: incidentLocation
          Status: stageOfControl
  - location: CA
    filename: CA_Fire_Perimeters_{DATE}.zip
    mapping:
      fields:
        Fire: fireId
        Name: fireId
        Location: fireArea
        Size: fireSize
        Status: fireStage
  - location: US
    filename: "WFIGS_Interagency_Perimeters_{DATE}.zip"
    mapping:
      fields:
        Fire: attr_Fir_6
        Name: attr_Inc_2
        Location: attr_Inc_4
        Size: attr_Incid
        Status: attr_Fir_2
      size_transform: acres_to_hectares
